config/routes.rb
Homestreetapp::Application.routes.draw do
  get "metrics/index"
  get "welcome/index"
  get 'partners/metrics', to: 'partners#metrics'
  get 'residents/metrics', to: 'residents#metrics'
   get 'residents/info', to: 'residents#info'

  root "welcome#index"
  devise_for :users
  resources :partners
  resources :residents do
    resources :donations
    resources :statuses
  end
  resources :donors do
    resources :donations
  end
  devise_scope :user do 
    get '/users/user_sign_up', to: 'devise/registrations#new', as:'new_donor_user_registration'
  end

  

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  belongs_to :user
  has_many :donations
  has_many :residents, :through => :donations
  validates_length_of :phone, :is => 10, allow_nil: true, allow_blank: true
  validates_format_of :email, with: /[a-zA-Z0-9]\@[a-zA-Z]{2,}\.[a-zA-Z]{2,}/, allow_nil: true, allow_blank: true
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  load_and_authorize_resource
  def new
    @donor = Donor.new
  end

  def create
    @donor = Donor.new(donor_params)
    if @donor.save
      redirect_to donors_path
    else
      render 'new'
    end
  end

  def edit
    @donor = Donor.find(params[:id])
    @residents = @donor.residents
  end

  def update
    @donor = Donor.find(params[:id])
    @residents = @donor.residents
    if @donor.update(donor_params)
      redirect_to donors_path
    else 
      render 'edit'
    end
  end

  def index
    @donors = Donor.all
  end

  def show
    @donor = Donor.find(params[:id])
    @residents = @donor.residents
  end
  def donor_params
    params.require(:donor).permit(:name, :org, :phone, :email, :email_updates, :phone_updates, :user_id)
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= bootstrap_form_for (@donor) do |f| %>
	<%= f.text_field :name %><br />
	<%= f.text_field :org %><br />
	<%= f.text_field :phone %><br />
	<%= f.text_field :email, :value => current_user.email %><br />
	<%= f.check_box :email_updates %><br />
	<%= f.check_box :phone_updates %>
	<%= f.hidden_field :user_id, :value => current_user.id %><br />
	<%= f.submit  class: "btn btn-sm btn-primary btn-block" %>


<% end %>

app/views/donors/create.html.erb
<h1>Donors#create</h1>
<p>Find me in app/views/donors/create.html.erb</p>

app/views/donors/edit.html.erb
<div class="container col-md-6 col-md-offset-3">
<h1> Edit Profile </h1>
<%= render partial: "form" %>
</div>

app/views/donors/index.html.erb
<h1> Donors </h1>

<% @donors.each do |p| %>
	<ul>
	<li><%= p.name %> with <%= p.donations.count %> to  <%= p.residents.count %> homeless people
	<%= link_to 'details', donor_path(p) %> <%= link_to 'edit', edit_donor_path(p) %>
		<% p.donations.each do |d| %>
			Donation Amount: <%= d.amount %>
		<% end %>
	</li>
	</ul>

<% end %>

app/views/donors/new.html.erb
<div class="container col-md-6 col-md-offset-3">
<h1> Create Profile </h1>
<%= render partial: "form" %>
</div>

app/views/donors/show.html.erb
<h1><%= @donor.name %></h1>
<br>
Organization: <%= @donor.org %>
<% if @donor.residents.count >0 %>
Donated to: 
<% @donor.residents.each do |d| %>
	<ul>
		<li><%= d.name %></li>
	</ul>
<% end %>
<% end %>

app/views/donors/update.html.erb
<h1>Donors#update</h1>
<p>Find me in app/views/donors/update.html.erb</p>