config/routes.rb
Homestreetapp::Application.routes.draw do
  get "metrics/index"
  get "welcome/index"
  get 'partners/metrics', to: 'partners#metrics'
  get 'residents/metrics', to: 'residents#metrics'
   get 'residents/info', to: 'residents#info'

  root "welcome#index"
  devise_for :users
  resources :partners
  resources :residents do
    resources :donations
    resources :statuses
  end
  resources :donors do
    resources :donations
  end
  devise_scope :user do 
    get '/users/user_sign_up', to: 'devise/registrations#new', as:'new_donor_user_registration'
  end

  

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  require 'oauth'
  before_action :find_resident, :except=> [:text_updates, :twitter_update, :status]

  def index
  @statuses = Status.all
  end
  def new
    @status = Status.new
  end

  def create
    @donor = @resident.donors
    @status = Status.new(status_params)
    if @status.save
      # UserMailer.send_status_email(@donor, @status, @resident)
      text_updates(@status.content, @donor)
      twitter_update(@resident.name, @status.content)
      redirect_to residents_path
    else
      render 'new'
    end
  end

  def find_resident 
    @resident = Resident.find(params[:resident_id])
  end 

  def show
    @resident = Resident.find(params[:resident_id])
    @status = Status.find(params[:id])
  end

  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])
  if @status.update(status_params)
      redirect_to resident_status_path(@resident, @status)
    else
      render 'edit'
    end
  end

  def text_updates(content, donors)
    @content = content
    # @account_sid = ENV["TWILIO_ID"]
    # @auth_token = ENV["TWILIO_SECRET"]
    @donors = donors
    @donors.each do |d|
      if d.phone_updates
        # set up a client to talk to the Twilio REST API 
        @client = Twilio::REST::Client.new ENV["TWILIO_ID"], ENV["TWILIO_SECRET"]  
        @client.account.messages.create({
          :from => ENV["TWILIO_PHONE"], 
          :to => "#{d.phone}",
          :body => "Message: #{@content}"
          })
      end
    end
  end

  def twitter_update(name, tweet)
    @name = name
    @tweet = tweet
    consumer_key = OAuth::Consumer.new(ENV["TWITTER_CONSUMER_KEY"],
      ENV["TWITTER_CONSUMER_SECRET"])
    access_token = OAuth::Token.new(ENV["TWITTER_ACCESS_TOKEN"],
      ENV["TWITTER_ACCESS_SECRET"])

    baseurl = "https://api.twitter.com"
    path    = "/1.1/statuses/update.json"
    address = URI("#{baseurl}#{path}")
    request = Net::HTTP::Post.new address.request_uri
    request.set_form_data(
      "status" => "#{@name.titleize}: #{@tweet}",
    )

    http             = Net::HTTP.new address.host, address.port
    http.use_ssl     = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    request.oauth! http, consumer_key, access_token
    http.start
    response = http.request request

    tweet = nil
    if response.code == '200' then
      tweet = JSON.parse(response.body)
      puts "Successfully sent #{tweet["text"]}"
    else
      puts "Could not send the Tweet! " +
      "Code:#{response.code} Body:#{response.body}"
    end
  end

  private

  def status_params
    params.require(:status).permit(:content, :resident_id)
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= bootstrap_form_for @status, url: {action: "create"} do |f| %>
	<%= f.text_area :content %><br />
	<%= f.hidden_field :resident_id, :value => @resident.id %>
	
	<%= f.submit class: "btn btn-primary btn-block" %>


<% end %>

app/views/statuses/create.html.erb
<h1>Statuses#create</h1>
<p>Find me in app/views/statuses/create.html.erb</p>

app/views/statuses/index.html.erb
<h1> Statuses </h1>
<% @statuses.each do |p| %>
	<ul>
	<li>
	<!-- converts time to readable format -->
	<% if Time.new.utc.year == p.created_at.to_s.split(/[^0-9]+/)[0].to_i%>
			<% if Time.new.utc.month == p.created_at.to_s.split(/[^0-9]+/)[1].to_i %>
				<% if Time.new.utc.day == p.created_at.to_s.split(/[^0-9]+/)[2].to_i %>
					<% if Time.new.utc.hour == p.created_at.to_s.split(/[^0-9]+/)[3].to_i %>
						<% if Time.new.utc.min == p.created_at.to_s.split(/[^0-9]+/)[4].to_i %>
						a few seconds ago
						<% else %>
						<%= Time.new.utc.min - p.created_at.to_s.split(/[^0-9]+/)[4].to_i %> minutes ago
						<% end %>
					<% else %>
						<%= Time.new.utc.hour - p.created_at.to_s.split(/[^0-9]+/)[3].to_i %> hours ago
					<% end %>
				<% else %>
					<%= Time.new.utc.day - p.created_at.to_s.split(/[^0-9]+/)[2].to_i %> days ago
				<% end %>
			<% else %> <%= Time.new.utc.month - p.created_at.to_s.split(/[^0-9]+/)[1].to_i %> months ago
			<% end %>
		<% else %>
		<%= Time.new.utc.year - p.created_at.to_s.split(/[^0-9]+/)[0].to_i %> years ago 
		<% end %>
	 : <%= p.content %> </li>
	<%= link_to 'details', resident_status_path(@resident, p) %> <%= link_to 'edit', edit_resident_status_path(@resident, p) %>
	</li>
	</ul>

<% end %>

app/views/statuses/new.html.erb
<div class="container col-md-6 col-md-offset-3">
<h1> Edit Profile </h1>
<%= render partial: "form" %>
</div>

app/views/statuses/show.html.erb
<h1>Statuses#show</h1>
<p>Find me in app/views/statuses/show.html.erb</p>