config/routes.rb
Homestreetapp::Application.routes.draw do
  get "metrics/index"
  get "welcome/index"
  get 'partners/metrics', to: 'partners#metrics'
  get 'residents/metrics', to: 'residents#metrics'
   get 'residents/info', to: 'residents#info'

  root "welcome#index"
  devise_for :users
  resources :partners
  resources :residents do
    resources :donations
    resources :statuses
  end
  resources :donors do
    resources :donations
  end
  devise_scope :user do 
    get '/users/user_sign_up', to: 'devise/registrations#new', as:'new_donor_user_registration'
  end

  

end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :user
  has_many :residents
  has_many :donations, :through => :residents
  has_many :donors, :through => :donations
  validates_format_of :email, with: /[a-zA-Z0-9]\@[a-zA-Z]{2,}\.[a-zA-Z]{2,}/
  validates_format_of :website, with: /\A(\w|[.])[^\W]\w{1,}\.[a-zA-Z]{2,}/
  validates_length_of :phone, :is => 10

  has_attached_file :image, 
            :style => { 
            :medium => "300x300>", :thumb => "100x100>" },
            :storage => :s3
            

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  load_and_authorize_resource

  respond_to :json, :html

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      respond_to do |format|
        format.html {UserMailer.welcome_email(@partner).deliver
          redirect_to partners_path}
        format.json {render json: @partner, status: :created}
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @partner = Partner.find(params[:id])
    @residents = @partner.residents
  end

  def update
    @partner = Partner.find(params[:id])
    @residents = @partner.residents
    if @partner.update(partner_params)
      respond_to do |format|
        format.html { redirect_to partners_path }
        format.json { render nothing: true, status: :no_content }
      end
   else
      respond_to do |format|
        format.html { render 'edit' }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @partners = PartnerReporting.find_by_sql('SELECT partners.id, partners.name, partners.org, partners.email, partners.address, SUM(amount), AVG(amount), MAX(amount), MIN(amount), COUNT(donations.id) FROM "donations" RIGHT OUTER JOIN residents ON "donations"."resident_id" = "residents"."id" RIGHT OUTER JOIN "partners" ON "residents"."partner_id" = partners.id GROUP BY partners.name, partners.id, partners.org, partners.email, partners.address')
    respond_with @partners
  end

  def metrics
    @partners = PartnerReporting.find_by_sql('SELECT partners.id, partners.name, partners.org, partners.email, partners.address, SUM(amount), AVG(amount), MAX(amount), MIN(amount), COUNT(donations.id) FROM "donations" RIGHT OUTER JOIN residents ON "donations"."resident_id" = "residents"."id" RIGHT OUTER JOIN "partners" ON "residents"."partner_id" = partners.id GROUP BY partners.name, partners.id, partners.org, partners.email, partners.address')
    respond_with @partners
  end


  def show
    @partner = Partner.find(params[:id])
    @residents = @partner.residents
    respond_with @partner
  end
  def partner_params
    params.require(:partner).permit(:name, :org, :address, :phone, :email, :website, :user_id, :image, :resident_id, :donations => [:amount])
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= bootstrap_form_for (@partner) do |f| %>
	<%= f.text_field :name %><br />
	<%= f.text_field :org %><br />
	<%= f.text_field :address %><br />
	<%= f.text_field :phone %><br />
	<%= f.text_field :email, :value => current_user.email %><br />
	<%= f.text_field :website %><br />
	<div class="field">
	  <%= f.file_field :image %>
    </div>
	<%= f.hidden_field :user_id, :value => current_user.id %><br />
	<%= f.submit class: "btn btn-primary btn-block" %>


<% end %>

app/views/partners/edit.html.erb
<div class="container col-md-6 col-md-offset-3">
<h1> Edit Profile </h1>

<%= render partial: "form" %>
</div>

app/views/partners/index.html.erb
<div ng-app="partner-app" class="container">


  <div ng-controller="PartnerCtrl">

    <button type="button" class="btn btn-lg btn-info" data-template="aside.html" data-placement="left" bs-aside="aside" data-container="body">Dashboard
    </button>

    <h2> Partners </h2>

     <div class="form-group">

        <input ng-model="searchPartner" type="text" class="form-control" placeholder="search partners">
          {{ searchPartner}}
      </div>
    <table class="table">
    <th>Name</th>
    <th>Organization</th>
    <th>Number Residents</th>
    <th>Details</th>

      <tbody>
      <tr ng-repeat="partner in partners | filter: searchPartner ">

        <td>
        {{partner.name}} 
        <div ng-show="partner.details">
          <dl>
    
            <dd>Email: {{partner.email}}</dd>   
    
            <dd>Address: {{partner.address}}</dd>
            <dt>Residents:</dt>
            <ul>
              <div ng-repeat="resident in partner.residents"><a href="/residents/{{resident.id}}">{{resident.name}}</a></div>
            </ul>

            

          </dl>
          </div></td>
        <td>{{partner.org}} </td>

        
        
        </td>
        <td>{{partner.residents.length}}</td>


        <td>
        <span ng-hide="!partner.details"><a ng-click="hidePartner(partner)">Hide</a></span>
        <span ng-hide="partner.details"><a ng-click="showPartner(partner)">Show</a></span>
        </td>
  
        
      </tr>
      </tbody>
      </table>
    
   

  </div>
</div>

app/views/partners/metrics.html.erb
<style>
	
	.rotate {

			/* Safari */
			-webkit-transform: rotate(-90deg);

			/* Firefox */
			-moz-transform: rotate(-90deg);

			/* IE */
			-ms-transform: rotate(-90deg);

			/* Opera */
			-o-transform: rotate(-90deg);

			/* Internet Explorer */
			filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);

			}
			.chart div {
				  font: 15px sans-serif;
				  text-align: left;
				  padding: 3px;
				  margin: 1px;
				  color: black;
			}
			.arc path {
  				stroke: #fff;
			}
			svg {
				margin-left: 30%;
			}


</style>

<div ng-app="partner-app" class="container">


  <div ng-controller="PartnerCtrl">

    <button type="button" class="btn btn-lg btn-info" data-template="aside.html" data-placement="left" bs-aside="aside" data-container="body">Dashboard
    </button>
    <button type="button" class="btn btn-lg btn-success" onclick="populateit()">Visualize Data</button>
<br></br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">By the Numbers</h3>
  </div>
  <div class="panel-body">
   <div class="row">
  		<div class="col-md-4 text-center">
  			<span class="glyphicon glyphicon-user"></span>  {{partners.length}} <br>
  			Total Partners
  		</div>
  		<div class="col-md-4 text-center">
  			<span class="glyphicon glyphicon-user"></span>  ${{avgdonation(partners) | number: 2}} <br>
  			Average Donations Raised	
  		</div>
  		<div class="col-md-4 text-center">
  			<span class="glyphicon glyphicon-user"></span>  {{avgresidents(partners) | number: 2}} <br>
  			Average Number of Residents
  		</div>
	</div>
  </div>
</div>

    <h2> Average Donation Size </h2>
<div ng-repeat="partner in partners">
	<strong>{{partner.name}}</strong><div class = donbox>${{partner.avg}}</div>
</div>
     <h2> Amount Raised per Partner</h2>

<div ng-repeat="partner in partners">
<div class="chart">
	{{partner.name}}<div class = totalbox>${{partner.sum}}</div>
</div>
</div>


  </div>
</div>

		<script>
		function populateit(){

		d3.json("metrics.json", function(error, json) {
			var raised = [];
			var avgdon = [];
			var partnames = [];
			partnerdata = json;
	
			for (i=0; i<partnerdata.length; i++){
				if(partnerdata[i].sum== null){
					partnerdata[i].sum = 0;
				}
				if(partnerdata[i].avg== null){
					partnerdata[i].avg = 0;
				}
			partnames.push(partnerdata[i].name);
			raised.push(partnerdata[i].sum);
			avgdon.push(partnerdata[i].avg);
			};
	
			
			applyD3Selectors(raised);
			applyD3avgSelectors(avgdon);
			piechart(raised, partnames);
			
		});

		
		function applyD3Selectors(x){
				// Put D3 magic here
				var raised = x;
				console.log(raised);
				
			d3.selectAll(".totalbox")
			    .data(raised)
			    .style("height", "30px").style("margin", 0).style("padding", 0).transition()
			    .style("background-color", function(d) {
			  		return "hsl(" + d*.2 + ",100%,50%)";
				})
				.text(function(d) {
        			return "$" + d;
   				})
			    .style("width", function(d, i) { return (d) + "px"; });
			};
		function applyD3avgSelectors(x){
				// Put D3 magic here
				var avgdon = x;
				console.log(avgdon);
				
			d3.selectAll(".donbox")
			    .data(avgdon)
			    .style("background-color", function(d) {
			  		return "hsl(" + d*.9 + ",100%,50%)";
				})
				.text(function(d) {
        			return "$" + Math.round(d);
   				})
			    .style("height", "30px").style("margin", 0).style("padding", 0).transition()
			    .style("width", function(d, i) { return (d) + "px"; });
			};
			function piechart(x,y){
				var w = 500,
				    h = 300,
				    r = Math.min(w, h) / 2;

				var color = d3.scale.ordinal()
				    .range(["#5DFC0A", "#FF3300", "#00FFCC", "#00FFCC", "#FF0066", "#FF944D", "#3366FF"]);
				data = x;
				theirnames= y;

				var vis = d3.select("body")
		        .append("svg:svg")              //create the SVG element inside the <body>
		        .data([data])                   //associate our data with the document
		            .attr("width", w)           //set the width and height of our visualization (these will be attributes of the <svg> tag
		            .attr("height", h)
		        .append("svg:g")                //make a group to hold our pie chart
		            .attr("transform", "translate(" + r + "," + r + ")")    //move the center of the pie chart from 0, 0 to radius, radius
		 
		    var arc = d3.svg.arc()              //this will create <path> elements for us using arc data
		        .outerRadius(r);
		 
		    var pie = d3.layout.pie()           //this will create arc data for us given a list of values
		 
		    var arcs = vis.selectAll("g.slice")     //this selects all <g> elements with class slice (there aren't any yet)
		        .data(pie)                          //associate the generated pie data (an array of arcs, each having startAngle, endAngle and value properties) 
		        .enter()                            
		            .append("svg:g")                
		                .attr("class", "slice");    
		 
		        arcs.append("svg:path")
		                .attr("fill", function(d, i) { return color(i); } ) 
		                .attr("d", arc);                                  
		 
		        arcs.append("svg:text")                                     
		                .attr("transform", function(d) {                    
		                d.innerRadius = 0;
		                d.outerRadius = r;
		                return "translate(" + arc.centroid(d) + ")";        
		            })
		            .attr("text-anchor", "middle")                         
		            .text(function(d, i) { return theirnames[i]; });        
				 
				};



		};
		

		</script>

app/views/partners/new.html.erb
<div class="container col-md-6 col-md-offset-3">
<h1> Create Profile </h1>

<%= render partial: "form" %>
</div>

app/views/partners/show.html.erb
<%= @partner.org %>
<%= image_tag @partner.image.url %>
<%= @partner.residents.count %>
<% @partner.residents.each do |r| %>
	<ul>
		<li>
		<%= link_to resident_path(r) do %>
		<%= r.name %>
		<% end %>
		</li>
	</ul>
<% end %>