config/routes.rb
Homestreetapp::Application.routes.draw do
  get "metrics/index"
  get "welcome/index"
  get 'partners/metrics', to: 'partners#metrics'
  get 'residents/metrics', to: 'residents#metrics'
   get 'residents/info', to: 'residents#info'

  root "welcome#index"
  devise_for :users
  resources :partners
  resources :residents do
    resources :donations
    resources :statuses
  end
  resources :donors do
    resources :donations
  end
  devise_scope :user do 
    get '/users/user_sign_up', to: 'devise/registrations#new', as:'new_donor_user_registration'
  end

  

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor
  belongs_to :resident

  validates_numericality_of :amount, only_integer: true

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def new
  	@resident = Resident.find(params[:resident_id])
  	@donation = Donation.new
  end

  def create
  	@resident = Resident.find(params[:resident_id])
    @donation = Donation.new(donation_params)
    if @donation.save
      redirect_to resident_donation_path(@resident, @donation)
    else
      render 'new'
    end
  end

  def show
    @resident = Resident.find(params[:resident_id])
    @donation = Donation.find(params[:id])
  end


  def donation_params
  	params.require(:donation).permit(:amount, :donor_id, :resident_id)
  end

  
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/braintree.erb
<h1>Donation Page</h1>
<html>
  <head>
  </head>
  <body>
    <h1>Braintree Credit Card Transaction Form</h1>
    <div>
      <form action="/create_transaction" method="POST" id="braintree-payment-form">
        <p>
          <label>Card Number</label>
          <input type="text" size="20" autocomplete="off" data-encrypted-name="number" />
        </p>
        <p>
          <label>CVV</label>
          <input type="text" size="4" autocomplete="off" data-encrypted-name="cvv" />
        </p>
        <p>
          <label>Expiration (MM/YYYY)</label>
          <input type="text" size="2" name="month" /> / <input type="text" size="4" name="year" />
        </p>
        <input type="submit" id="submit" />
      </form>
    </div>
    <script src="https://js.braintreegateway.com/v1/braintree.js"></script>
    <script>
      var braintree = Braintree.create("MIIBCgKCAQEAt4lQLovtDgRjWecJybJGxQZ4LiTjVQ5Y3Ufp8AXQ/evqV/f3g2S5EAhLhXTUpNbj/ybU+xubEnANTtXxCuBZcb6B3Rx3LORhnkyu2zIbtmTgkuHV8BfjDMhL0d0PY7a2xL5tPWQhHRt3c8NEtqUk3lSgaWLm2INGgu5zBUi1zZlZ1KLosTidluF/OA+CiWOCqT1hgXwK2sCW1Bf78e7wLVjGxZastz7ml1MmT1QsDuxT1GZCsDiUI04xHdn2qBr23UnImQGaifpTXrq6IqvOH9bqcDGFQhr03opJ8oJgFg8vqQsAgNyadUvbE1JjHdUcgg0+fUEcOxDnEOEknlW68QIDAQAB");
      braintree.onSubmitEncryptForm('braintree-payment-form');
    </script>
  </body>
</html>

app/views/donations/create.html.erb
<h1>Donations#create</h1>
<p>Find me in app/views/donations/create.html.erb</p>

app/views/donations/index.html.erb
<h1>Look at all the $$$!</h1>

<h3>Donations</h3>
	<% @donations.each do |d| %>
				<tr>			
					<td class="links" class="rows">
						<%= link_to d.name, d,'data-no-turbolink' => true %></td>
					<td class="rows"><%= d.org %></td>
					<td class="rows"><%= d.amount%></td>
					</td>
			
				</tr>

	
				<%end %>

app/views/donations/new.html.erb
<div class="container">
<div class="col-md-2 col-md-offset-5 text-center">
<%= bootstrap_form_for @donation, url: {action: "create"} do |f| %>
	<%= f.text_field :amount, prepend: '$' %><br />
	<%= f.hidden_field :resident_id, :value => @resident.id %>
	<% if Donor.where(:user_id => current_user.id)[0] != nil %>
	<%= f.hidden_field :donor_id, :value => Donor.where(:user_id => current_user.id)[0].id %>
	<% end %>
	<%= f.submit 'Donate', class: "btn btn-success btn-lg"%>


<% end %>
</div>
</div>

app/views/donations/show.html.erb
<div class="container">
<div class="container col-md-8 col-md-offset-2 text-center">

<div class="jumbotron success">
<h1> Thanks for donating!</h1>

<h1><span class="glyphicon glyphicon-heart"></span></h1>

<h4> <%= @resident.name %> really appreciates your generous donation of $<%= @donation.amount %>! </h4>

<% if @donation.donor_id == nil %> 
<h4> Fill out <%= link_to 'your profile', new_donor_path %> to receive updates on <%= @resident.name %> </h4>
<% else %>
<h4> Turn on updates in <%= link_to 'your profile', edit_donor_path(@donation.donor_id) %> to get filled in on how <%= @resident.name %> is doing</h4>
<% end %>

</div>
</div>